### ISSUE TITLE
trouble on MAC OS X"Illegal instruction: 4"

### ISSUE THREAD

**Issue by mentore77** [ralph-group/mucloud#10]
Hello! I am new to MuCloud and AWS, and I'm having some trouble launching MuCloud on my laptop with the OS X EL Capitan 10.11.3. I've followed the instructions for installing MuCloud, but when I'm trying to launch the following command from terminal

cd /Users/User1/Desktop/mucloud 
./mucloud --help

I receive the error message

Illegal instruction: 4

Do you have a suggestion?

Thank you in advance

**Comment by cjermain** [comment]
Thanks for reporting this. It looks like the error code has to do with the compiling step (following [StackOverflow](http://stackoverflow.com/questions/14268887/what-is-the-illegal-instruction-4-error-and-why-does-mmacosx-version-min-10)), and may be that you have a newer OSX version.

@grahamrow, which version of MacOSX was MuCloud 1.2 compiled for?

**Comment by grahamrow** [comment]
Original compilation was on 10.10.

@mentore77 I'll try recompling on my laptop (currently stuck at 10.10.5) with some of the suggested compiler flags, but if that doesn't work I can try on my desktop (10.11.xx) once I'm back from travel.

**Comment by grahamrow** [comment]
Could you try this version [mucloud-v1.2-PyInstaller3.1.1.zip](https://github.com/ralph-group/mucloud/files/163428/mucloud-v1.2-PyInstaller3.1.1.zip)?

**Comment by mentore77** [comment]
I am really sorry for the delay, few days ago I have tried the linked code ant it works! 
Thanks

**Comment by cjermain** [comment]
I'm closing this since it appears resolved. Feel free to re-open if not.
