### ISSUE TITLE
Issues compiling Mumax3 on AWS instance

### ISSUE THREAD

**Issue by Lizatre** [ralph-group/mucloud#12]
I am trying to run mumax3 simulations on an Amazon Instance after changing the mumax3 source code (specifically some files within the engine module). However, I am not able to recompile Mumax3 with the changes.

I started out using the [MIT mucloud](http://ralph-group.github.io/mucloud/) software which provides an AWS Image with the mumax3 binaries loaded in already. After adding my changes I attempted to build the code from the 'src/' directory on the instance, however, I started getting GPU incompatibility problems:
nvcc fatal   : Unsupported gpu architecture 'compute_52'

and also:

cmd/mumax3-fft/spatial.go:10:2: cannot find package "github.com/barnex/matrix" in any of:
    /usr/lib/go/src/pkg/github.com/barnex/matrix (from $GOROOT)
    /home/ubuntu/src/github.com/barnex/matrix (from $GOPATH)

I've also tried compiling the binaries myself (following the directions on the mumax3 readme) on an Amazon instance using the [AWS Marketplace Nvidia-Cuda Image](https://aws.amazon.com/marketplace/pp/B01LZMLK1K). However, on that OS I was not able to install all the necessary dependencies, including go or nvidia-cuda-toolkit.

I was wondering if you have any pointers about dealing with this issue? Thank you!

**Comment by cjermain** [comment]
@Lizatre, after our email conversation did you have success compiling on the instance? I will close this issue if so.

**Comment by Lizatre** [comment]
Yes I did, thank you very much for your help!

**Comment by cjermain** [comment]
I'm glad it worked!
