### ISSUE TITLE
uploading .ovf files to AWS

### ISSUE THREAD

**Issue by aoronbarlow** [ralph-group/mucloud#13]
Hi, 
I am using mucloud_1.2_windows and trying to load initial magnetization file to the AWS using m.LoadFile('m_fin.ovf') but simulation does not run when I add this line to the script. Other than that the script works fine.

m.LoadFile("D:\\LLG\\mumax\\mucloud_1.2_windows\\tests\\m_fin.ovf")  //This doesnt work .
m.LoadFile("m_fin.ovf") //This doesnt work either.

Colin stated that 
''MuCloud does not support uploading additional files at this point. However, this would be a great feature to have. Adding this feature should be fairly straightforward by modifying mucloud.py. ''

When do you thin this could be implemented ?

Thanks

Aoron

**Comment by cjermain** [comment]
@aoronbarlow, thanks for reporting this issue on GitHub.

Checkout line [207 in mucloud.py](https://github.com/ralph-group/mucloud/blob/master/mucloud.py#L207) where the input file is put onto the AWS instance. This needs to be extended to put additional files, such as your `m_fin.ovf` file. Consider extending the `run` method of `Instance` to accept optional files.

As this is an open-source project, you are welcome to implement it or see if anyone else is interested to do so. PR welcome.

**Comment by cjermain** [comment]
This project is being archived, since it is no longer maintained. Feel free to fork.
