### ISSUE TITLE
Error while loading geometry as image

### ISSUE THREAD

**Issue by guruvenkat7** [ralph-group/mucloud#15]
Hi,

I was running a Mumax3 program (which has worked before on a computer with a GPU), using MuCloud. However, the program stops abruptly in between at a particular line of the code (You can see this line in the attached snapshot). The line involves loading the geometry a B&W image.

This makes me wonder whether it is a problem of the version of Mumax3 that MuCloud is running. The docs tell me that MuCloud is running Mumax 3.9c. This version of Mumax3 may not support this form of geometry creation.

Let me know if you need more information and thanks for the help.
![mumax3-imageshape-error](https://user-images.githubusercontent.com/17523620/47306772-3ff5af80-d625-11e8-9b89-f3432996f9f2.png)

**Comment by cjermain** [comment]
This project is being archived, since it is no longer maintained. Feel free to fork.
