### ISSUE TITLE
InvalidParameterValue error while launching a new instance

### ISSUE THREAD

**Issue by cogtepsum** [ralph-group/mucloud#8]
Hello! I am very new to MuCloud and AWS, and I'm having some trouble launching a new instance. I use virtual python 2.7.10 environment on Ubuntu 14.04.
I've followed the instructions for installing MuCloud, but when I'm trying to launch a new instance with ```python mucloud.py launch``` I get this error
```
Traceback (most recent call last):
  File "mucloud.py", line 645, in <module>
    args.func(args)
  File "mucloud.py", line 521, in launch_instance
    instance = Instance.launch()
  File "mucloud.py", line 408, in launch
    security_groups=config.get('EC2', 'SecurityGroups')
  File "/home/user/miniconda3/envs/fenics34/lib/python2.7/site-packages/boto/ec2/connection.py", line 973, in run_instances
    verb='POST')
  File "/home/user/miniconda3/envs/fenics34/lib/python2.7/site-packages/boto/connection.py", line 1207, in get_object
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Value () for parameter groupId is invalid. The value cannot be empty</Message></Error></Errors><RequestID>fb75e496-e565-42d3-85ce-3871ceb904ae</RequestID></Response>
```
What can be a problem in this case? Thank you in advance!

**Comment by cjermain** [comment]
Did you successfully follow the [instructions for setting up AWS](http://ralph-group.github.io/mucloud/setup_aws/)?

What region were you using when setting up AWS? The top right-hand corner of the AWS console displays the region. We haven't yet included specific instructions on working in different regions. I created the AMI (the image that is used for the virtual computer) on U.S. East (N. Virginia), which is also set in the `config.ini` file. To have the AMI accessible in another region, it will need to be copied. I can write up some documentation on this if this is indeed the problem.

**Comment by cogtepsum** [comment]
Thank you for your answer!

I was thinking that region is a problem, so I've tried to change it in config file but got only a different error (as I said, I'm quite new to AWS =)). I will change the region and redo all of the instructions right now. Thank you again!

**Comment by cogtepsum** [comment]
I'm getting another error `The image id '[ami-3437145c]' does not exist` now. I searched through community AMIs for "mucloud" and found `ami-b47a79dc`. Can I use this image?

**Comment by cjermain** [comment]
Yes, the new AMI for MuCloud 1.1 is `ami-b47a79dc`. I'll update this in the releases. Can you access that AMI from a different region?

**Comment by cogtepsum** [comment]
This new AMI works from U.S.East region, thank you! Another `ami-1d13d776` seems to be working as well.

Regarding to accessing it from another region, I've done this: changed `config.ini` file to use my keys and security group from U.S.West (Oregon) region, but without changing `Image` and `Region` fields. That gave me the old `Value () for parameter groupId is invalid. The value cannot be empty` error. After that I've changed `Region` field to `us-west-2` and it gave me `The image id '[ami-b47a79dc]' does not exist` error. Either I've done something wrong with a region changing or these AMIs are not available from another region.
